### ISSUE TITLE
I’ve learned a lot from your code and really appreciate it!

### ISSUE THREAD

**Issue by hstdt** [anconaesselmann/NestedTable#1]
Hi, there.

I’ve learned a lot how to use TableRowContent and more, Here are some observations that might be helpful:

I noticed that you’re using custom styles for “chevron.down” and “chevron.right” along with onHover to listen for disclosure. However, based on your amazing code, I found out that we could use DisclosureTableRow with built-in support for nesting and expanded style to directly handle disclosure listening for all platforms.

![CleanShot 2024-11-11 at 16 51 36@2x](https://github.com/user-attachments/assets/b56dd313-6aa9-4b9d-b5ae-87bb58e6a446)

Thank you again for the inspiration!

**Comment by anconaesselmann** [comment]
Cool, tank you @hstdt  for letting me know! I was not aware of DisclosureTableRow. I'll take a look. I am currently working on something unrelated so it might take me a bit of time to get back to this. I am impressed you were able to make use of my thoroughly undocumented project. How did you find this if I may ask?

**Comment by hstdt** [comment]
I'm glad this information is helpful.

As for how I found it, I searched for examples of using nested TableRowContent, with only a few relevant examples, but your code is exactly what I want!

![CleanShot 2024-11-13 at 10 20 29@2x](https://github.com/user-attachments/assets/490de4cf-cbeb-4da8-abd1-b894a8948f8c)
